### ISSUE TITLE
auto synergy toggle

### ISSUE THREAD

**Issue by xMathayus** [256shadesofgrey/eso-light-attack-weave#19]
Is it possible to add an auto synergy toggle option within this script? as I only toggle this on while in battle?

**Comment by 256shadesofgrey** [comment]
I do not intend to implement any interactions with synergies since they do not have anything to do with LA weaving. Also there are cases when certain synergies should not be used without full intent (various teleportation synergies as well as special mechanics in trials and dungeons), and the script currently does not get any information from the game, so it would be a lot of work to implement it in a way that doesn't negatively impact the gameplay.
