### ISSUE TITLE
Which AutoHotkey version is required?

### ISSUE THREAD

**Issue by 7efneBepMM2uGhfzmGpK** [256shadesofgrey/eso-light-attack-weave#4]
Tried several and I can't get the script executed.

Tried AH2, AH 1.1.32.00 and AH 1.0.48.05 x86.
Any of these versions print out a different error message.

This is the one I get from the latest stable version 1.1.32.00.
![image](https://user-images.githubusercontent.com/65942547/82870333-0cc97f80-9f30-11ea-9bd0-256aea1172a9.png)

**Comment by 256shadesofgrey** [comment]
AH2 is in beta, I have not tried using it. Any version of AH that I used in the past 2 years works. The one I am running right now is 1.1.31.01.

But I don't think that the error shown has anything to do with the AH version. If you look at the line 144 that the error refers to, it is very different from the line that is printed in the error. You probably downloaded the script incorrectly. It looks like you did a right click -> "save as" action in the browser right in the list of files in the top level of the page, which downloads the web page displaying the file contents nicely formatted rather than the file itself. Either use git and do `git clone https://github.com/256shadesofgrey/eso-light-attack-weave.git` or open the eso-light-attack-weave.ahk file normally in the browser, then press the "raw" button at the top of the frame showing the file content (in the same part that is showing the total number of lines in the file and its size). Then right click anywhere on the page and do "save as". Make sure the file ends with ".ahk", because chrome adds ".txt" at the end.

**Comment by 7efneBepMM2uGhfzmGpK** [comment]
Damn that actually was the problem. I did do the right click -> save as function. Now I opened the raw file, then did right click -> save as and renamed the .txt file. et voila it works.
Now the servers just have to go live!

Thank you very much.

**Comment by iSpotless** [comment]
So I am trying to get this macro to work and for some reason I am having the hardest time. Downloaded the file, made sure it had .ahk and had AutoHotKey running but it still wont run for me, maybe I am missing something. I use my 1 button to cast a spell and no attack comes out
