### ISSUE TITLE
bit misses light attacks

### ISSUE THREAD

**Issue by MrMcBad** [256shadesofgrey/eso-light-attack-weave#6]
hi the bot seems to be missing some light attacks on specific skills when at base values, id rather not raise the value that inputs the light attack above 100ms is there anything i can do

**Comment by MrMcBad** [comment]
> hi the bot seems to be missing some light attacks on specific skills when at base values, id rather not raise the value that inputs the light attack above 100ms is there anything i can do

after further experimentation it seems to be happening when i bar swap

**Comment by 256shadesofgrey** [comment]
There are multiple values you can adjust. `msDelay` sets the amount of time that passes between the light attack and the skill. `msGlobalCooldown` is maybe somewhat misleadingly named, but it sets the time between the skill activation and the next light attack. When doing a rotation quickly `msBarSwapCooldown` is masked by the skill cooldown, because those can happen simultaneously, but if you're slow it's basically delaying the next skill activation by up to the amount set in this value. You can adjust these values to whatever works for you.

But keep in mind, certain skills have longer animations, and so the default settings do not work for those skills (for example volley from the bow skill line). When relying on the macro to time the LAs, if you press a skill key right after volley, at the time the macro thinks that it's time to use the next skill, your game is still playing the animation of volley, and skills have priority over LAs, so the LA will be skipped, and the following skill queued by the game right after. You can fix it by increasing the timers.

But of course increasing the timers means you'll use other skills slower, and it might result in a net DPS loss. So the timers are a tradeoff between speed and reliability.

**Comment by MrMcBad** [comment]
so if i start on the bar thats having the issue there is no problem if the bug is happening all you have to do is left click manually, after swapping bars without changing any numbers
