### ISSUE TITLE
Hiding HUD and going into character screen when swapping bar with mouse5/xbutton2

### ISSUE THREAD

**Issue by er1cmit1** [256shadesofgrey/eso-light-attack-weave#9]
Hello,

i changed barswap key to XButton2, since i am swapping my bar with Mouse5 ingame. But everytime i do, my hud vanishes and a screen is brought up, which i think is the character screen, since it is zoomed on my char. 
Walk/run is also being toggled.
When i press barswap (mouse5) again, everything reverts back.

Cannot troubleshoot and solve it myself sadly :/

**Comment by er1cmit1** [comment]
Just tested a bit more and it pressed N (walk/run), O (friends), 2 and B (hide HUD) when i press Mouse 5 with XButton1 put into the script for barswap.

**Comment by 256shadesofgrey** [comment]
Sounds to me like you forgot to remove the \` before the XButton1. The \` is the escape character in autohotkey, so that's why you need to put it twice there to indicate the \` key instead of escaping ". If you use some other key, you have to remove it. It should say "XButton1", not "\`XButton1".

**Comment by er1cmit1** [comment]
Thanks for the answer. I attached a picture of how it looks in the script. I think it is written correctly there without the "`". I should mention that i have the german qwertz layout. Maybe this is causing problems?
![Unbenannt](https://user-images.githubusercontent.com/78907134/107637735-e6d73d00-6c6e-11eb-989e-732e8ebc6667.PNG)

**Comment by 256shadesofgrey** [comment]
Looks correct. I'll test it later today to see if I get the same kind of behavior.

**Comment by er1cmit1** [comment]
Thank you a lot in advance!

**Comment by 256shadesofgrey** [comment]
I just tested it, can confirm that it does strange things. But sadly I can't think of a way to fix it properly. You could do a bit of a hack to make it work for you specifically by binding some other key to bar swap in game (say B for the purposes of this example), and instead of doing this: https://github.com/256shadesofgrey/eso-light-attack-weave/blob/44c0a089d9555aa2ede0adba18b93389e346887e/eso-light-attack-weave.ahk#L275
You do this in that line:
```
Send, b
```
This way the script will still clear the queue when you use XButton2, but instead of sending XButton2 it will send B, which if you also keybind to bar swap, will have the desired effect in the game.

**Comment by er1cmit1** [comment]
Thx a lot, it is working now with your recommended fix :)
